#!/usr/bin/env python3
"""
Self-host Baloo 2 and Nunito.

    python3 tools/fetch_fonts.py

Downloads the woff2 files Google Fonts serves for the weights this game uses,
writes them to assets/fonts/, and rewrites assets/fonts.css with matching
@font-face rules. Run it once, on a machine with internet access; after that
the game has no third-party dependency at all.

Why bother: a school network that blocks fonts.googleapis.com currently makes
every heading fall back, and the same page then renders differently on the
classroom iPads than it does on your laptop. Self-hosting removes the variable.

Both families are licensed under the SIL Open Font License, which permits
redistribution — the licence text is downloaded alongside them.
"""
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
FONT_DIR = os.path.join(REPO, "assets", "fonts")
CSS_OUT = os.path.join(REPO, "assets", "fonts.css")

CSS_URL = ("https://fonts.googleapis.com/css2"
           "?family=Baloo+2:wght@500;600;700;800"
           "&family=Nunito:wght@400;600;700;800"
           "&display=swap")

# Google serves different formats by User-Agent. This one gets woff2 with the
# full unicode-range split; a bare urllib UA gets ancient TTF instead.
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")

LICENCE = "https://raw.githubusercontent.com/google/fonts/main/ofl/baloo2/OFL.txt"


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        data = r.read()
    return data if binary else data.decode("utf-8")


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    try:
        css = get(CSS_URL)
    except Exception as e:
        sys.exit(f"Could not reach Google Fonts ({e}).\n"
                 "Run this on a machine with internet access, or download the "
                 "woff2 files by hand and write assets/fonts.css yourself.")

    blocks = re.findall(r"@font-face\s*\{[^}]*\}", css)
    if not blocks:
        sys.exit("No @font-face rules in the response — the API shape changed.")

    out, seen, count = [], {}, 0
    for block in blocks:
        m = re.search(r"src:\s*url\((https://[^)]+\.woff2)\)", block)
        fam = re.search(r"font-family:\s*'([^']+)'", block)
        wgt = re.search(r"font-weight:\s*(\d+)", block)
        if not (m and fam and wgt):
            continue
        url = m.group(1)
        # One file per family+weight; the unicode-range subsets repeat the same
        # URL for latin and latin-ext, so dedupe on the URL itself.
        if url in seen:
            name = seen[url]
        else:
            name = f"{fam.group(1).replace(' ', '')}-{wgt.group(1)}.woff2"
            with open(os.path.join(FONT_DIR, name), "wb") as f:
                f.write(get(url, binary=True))
            seen[url] = name
            count += 1
        out.append(block.replace(f"url({url})", f"url(fonts/{name})"))

    header = (
        "/* Generated by tools/fetch_fonts.py — do not hand-edit.\n"
        " * Baloo 2 and Nunito, SIL Open Font License 1.1.\n"
        " * Re-run the script to refresh. */\n\n")
    with open(CSS_OUT, "w", encoding="utf-8") as f:
        f.write(header + "\n".join(out) + "\n")

    try:
        with open(os.path.join(FONT_DIR, "OFL.txt"), "w", encoding="utf-8") as f:
            f.write(get(LICENCE))
    except Exception:
        print("  (could not fetch the licence text — add OFL.txt by hand)")

    print(f"{count} font files -> assets/fonts/")
    print(f"{len(out)} @font-face rules -> assets/fonts.css")
    print("\nNow remove the Google Fonts <link> from index.html — the local "
          "copy has taken over and the remote one only slows the page down.")


if __name__ == "__main__":
    main()
